//  Copyright 2025-2026 JesseTheCatLover. All Rights Reserved.

#pragma once
#include <cstdint>
#include <string>

#include "Serialization/SerializeUtilities.h"
#include "Reflection/RETypeRegistry.h"
#include "Reflection/JReflectionSerialization.h"
#include "Utilities/UUUID.h"

struct REType;

/**
 * @class JCoreObject
 * @brief Base class for all engine objects that support identity, reflection, and serialization.
 *
 * JCoreObject provides:
 *  - A unique runtime ID (fast integer)
 *  - A persistent UUID used for load/save identification
 *  - Runtime type information via REType (generated by JReflectGen)
 *  - Automatic reflection-based serialization for all JPROPERTY() fields
 *
 * Derived classes may override SerializeCustom() and DeserializeCustom() to handle
 * non-reflected or special-case data.
 */
class JCoreObject
{
    friend class SerializationSubsystem;
    friend class SceneManager;

public:
    virtual ~JCoreObject() = default;

    // ---------------- Reflection ----------------
    // Implemented by generated code in each reflected derived class.
    [[nodiscard]] virtual const REType* GetREType() const = 0;

    template<typename T>
    bool IsA() const
    {
        const auto* self = GetREType();
        const auto* target = T::StaticREType();
        return RETypeRegistry::Get().IsDerivedFrom(self, target);
    }

    template<typename T>
    T* Cast()
    {
        return IsA<T>() ? static_cast<T*>(this) : nullptr;
    }

    template<typename T>
    const T* Cast() const
    {
        return IsA<T>() ? static_cast<const T*>(this) : nullptr;
    }

    // ---------------- Identity ----------------
    [[nodiscard]] uint64_t GetRuntimeID() const { return m_ID; }
    void SetRuntimeID(uint64_t id) { m_ID = id; }

    [[nodiscard]] const std::string& GetUUID() const { return m_UUID; }

protected:
    JCoreObject()
        : m_ID(++m_NextID)
        , m_UUID(UUUID::GenerateUUID())
    {}

    virtual void SerializeCustom(class JsonWriter& writer) const {}
    virtual void DeserializeCustom(const class JsonReader& reader) {}
    virtual void PostLoad() {}

private:
    uint64_t m_ID = 0;         ///< runtime-only ID
    std::string m_UUID;        ///< serialized stable and unique UUID
    inline static uint64_t m_NextID = 0;

    void SerializeJObject(class JsonWriter& writer) const
    {
        JReflectionSerialization::SerializeReflectedProperties(writer, *this);
        SerializeCustom(writer);
    }

    void DeserializeJObject(const class JsonReader& reader)
    {
        JReflectionSerialization::DeserializeReflectedProperties(reader, *this);
        DeserializeCustom(reader);
        PostLoad();
    }
};